### ISSUE TITLE
Tests failing because of `window.document`

### ISSUE THREAD

**Issue by MierenManz** [MierenManz/EventSource#4]
```json
{
  "name": "EventSource: close(), test events",
  "status": 1,
  "message": "document.getElementsByTagName is not a function",
  "stack": "TypeError: document.getElementsByTagName is not a function\n    at get_script_url (http://web-platform.test:8000/resources/testharness.js:3978:32)\n    at get_stack (http://web-platform.test:8000/resources/testharness.js:3801:26)\n    at new AssertionError (http://web-platform.test:8000/resources/testharness.js:3773:22)\n    at assert (http://web-platform.test:8000/resources/testharness.js:3763:19)\n    at assert_equals (http://web-platform.test:8000/resources/testharness.js:1242:13)\n    at assert_wrapper (http://web-platform.test:8000/resources/testharness.js:1186:30)\n    at Test.<anonymous> (http://web-platform.test:8000/eventsource/eventsource-close.htm#0:56:15)\n    at Test.step (http://web-platform.test:8000/resources/testharness.js:2087:25)\n    at EventSource.onmessage (http://web-platform.test:8000/resources/testharness.js:2114:35)\n    at EventSource.#fetch (file:///home/skyler/coding/jsts/eventsource/mod.ts:158:44)"
}
```
This is the full error stacktrace and it seems it is caused by the test and not the actual code
```
TypeError: document.getElementsByTagName is not a function
    at get_script_url (http://web-platform.test:8000/resources/testharness.js:3978:32)
    at get_stack (http://web-platform.test:8000/resources/testharness.js:3801:26)
    at new AssertionError (http://web-platform.test:8000/resources/testharness.js:3773:22)
    at assert (http://web-platform.test:8000/resources/testharness.js:3763:19) 
    at assert_equals (http://web-platform.test:8000/resources/testharness.js:1242:13)
    at assert_wrapper (http://web-platform.test:8000/resources/testharness.js:1186:30)
    at Test.<anonymous> (http://web-platform.test:8000/eventsource/eventsource-close.htm#0:56:15)
    at Test.step (http://web-platform.test:8000/resources/testharness.js:2087:25) 
    at EventSource.onmessage (http://web-platform.test:8000/resources/testharness.js:2114:35)
    at EventSource.#fetch (file:///home/skyler/coding/jsts/eventsource/mod.ts:158:44)
```

**Comment by MierenManz** [comment]
it seems to be the `get_script_url()` from
http://web-platform.test:8000/resources/testharness.js

```js
function get_script_url()
     {
         if (!('document' in global_scope)) {
             return undefined;
         }
 
         var scripts = document.getElementsByTagName("script");
         for (var i = 0; i < scripts.length; i++) {
 ```
This is how the script starts. We cannot remove the DOM from this script because it is used for the test name :/
If anyone has suggestions. Let me know cuz I have no idea

**Comment by andreubotella** [comment]
Some of the *.html tests depend on `document.title` for no good reason really, so I polyfilled that in the bundle (https://github.com/MierenManz/EventSource/blob/main/wpt/util/runner.ts#L215-L223), but apparently testharness.js is switching on the presence of a `document` global in various places. Defining `document` after testharness.js runs fixed some of the issues, but some of the detection happens at runtime. The solution to this is to change the WPT tests to not depend on `document.title`.

I'll open PRs on WPT for that.

**Comment by MierenManz** [comment]
Okay, would there be something that we could do in the mean time?
Because I find it really annoying that we have 11 tests that cannot be run likely because of this.
